language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - yarn run check
  - yarn build
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
