language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - yarn run check
  - yarn build
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls
deploy:
  provider: netlify
  skip_cleanup: true
  auth: $netlify_token
  local_dir: build
  edge: true
