version: "3"

services:
  website:
    image: nginx:alpine
    container_name: "nginx"
    restart: on-failure
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build/:/app/
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
