export enum ICON_TYPES {
  PHONE = 'phone',
  GLASSES = 'glasses',
  USER = 'user',
  MONITOR = 'monitor',
  EDIT = 'edit',
  DOWNLOAD = 'download',
  WORK = 'work',
  ROCKET = 'inclined-rocket',
  DATABASE = 'database',
  COMPUTER = 'computer',
  ITERATION = 'iteration',
  ENVELOPE = 'envelope',
  ADDRESS = 'address',
  SPEEDOMETER = 'speedometer',
  MORTARBOARD = 'mortarboard',
  CONTRACT = 'contract',
  FACEBOOK = 'facebook-logo',
  GITHUB = 'github-logo',
  TWITTER = 'twitter',
}
